entrypoint: bundle exec rackup -E production -p 8080 config.ru
runtime: ruby
vm: true

# Scaling Config.
automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 60

# Network Settings.
network:
  instance_tag: main-engine

