entrypoint: bundle exec rackup -p $PORT
runtime: ruby
vm: true

# Scaling Config.
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic

