sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: railsapp
  password: <%= ENV['MYSQL_PASS'] %>
  host: 173.194.245.18 # GCP CloudSQL Server

development:
  <<: *sqlite
  database: db/development.sqlite3
#  <<: *mysql
#  database: cloud-sync-database-dev

test:
  <<: *sqlite
  database: db/test.sqlite3

production:
  <<: *mysql
  database: cloud-sync-database

