# PostgreSQL on production environment.

sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: cloud-sync-db
  username: postgres
  password: <%= ENV['POSTGRESQL_ADMIN_PASS'] %>
  host: 146.148.110.51 # GCP PostgreSQL Server

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

production:
#  <<: *postgres
  <<: *sqlite
# for DEBUG
#  username: railsdev
#  password: railsdev
#  host: localhost
# TEMP
  database: db/production.sqlite3

