// System Test for Architecture Map Web.

// ARGs. ([0] == "node", [1] == file name)
const isHeadless = process.argv[2] == "--headless";

// Target .html generated by npm run build.
const targetUrl = "localhost:8080/architecture_map.html";

// Setup chrome web driver.
const webdriver = require("selenium-webdriver");
const chrome = require("selenium-webdriver/chrome");
const options = new chrome.Options();
options.addArguments( [
    "--log-level=ALL",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-gpu",
    "disable-infobars",
] );
if (isHeadless) {
  options.addArguments( [ "--headless" ] );
}
const driver = new webdriver.Builder()
    .forBrowser("chrome")
    .setChromeOptions(options)
    .build();



// Sample.
driver.get(targetUrl).then(function() {
  driver.quit();
});

