// System Test for Architecture Map Web.

import { prepareWebDriver, releaseWebDriver } from "./web_driver_loader";
import { ThenableWebDriver, By, until } from "selenium-webdriver";
import expect = require("expect.js");
import * as assert from "assert";

// ARGs. ([0] == "node", [1] == mocha, [2] == file name)
const IS_HEADLESS = process.argv.some( (arg) => {
  return arg == "--headless";
} );

// Target .html generated by npm run build.
const TARGET_URL = "http://localhost:8080/architecture_map.html";
const LOAD_TIMEOUT_MILLIS = 5000;

//// E2E SYSTEM TEST ////

describe("Test Architecture Map Web", () => {
  var driver: ThenableWebDriver;

  before( () => {
    driver = prepareWebDriver(IS_HEADLESS);
  } );

  after( () => {
    releaseWebDriver(driver);
  } );

  it("get root", async function() {
    await driver.get(TARGET_URL);

    let title = await driver.getTitle();

    expect(title).to.be("Architecture Map");

  } );



} );

